### ISSUE TITLE
Handling of %20

### ISSUE THREAD

**Issue by michaelhkay** [sindresorhus/filenamify#15]
Am I right in thinking this library makes no attempt to convert `My%20Documents` to `My Documents`? Is that by design?

**Comment by papb** [comment]
Yes, I guess this is by design. `%` is not a valid character, files can be named `foo%20bar.txt` without any problem. 

Even though I see your point, that `%20` could be normalized to a space, and other percent-enconded values could be converted as well... But since the goal of this library is simply to generate valid filenames, it does not have to do anything with `%20`.

**Comment by michaelhkay** [comment]
Fair enough. What we need is something that approximates to round-tripping between filenames and URIs, and it seems this library isn't it. Yes, of course I know perfect round-tripping isn't possible for the reasons you give, we just have to do the best we can.

**Comment by sindresorhus** [comment]
You can just run it through `decodeURIComponent` first, or use https://github.com/sindresorhus/filenamify-url
