### ISSUE TITLE
Cannot find module 'filenamify/browser' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by sagar-gavhane** [sindresorhus/filenamify#26]
Hey @sindresorhus,

I'm new to this library and want to use `filenamify` in the TypeScript based React project. As per README.md file, I'm importing `filenamify` from `filenamify/browser` but it throwing a `Cannot find module 'filenamify/browser'` error.

Is there any workaround to this issue?

**Comment by sindresorhus** [comment]
This is a problem with your build tool. It needs to support the `exports` property: https://github.com/sindresorhus/filenamify/blob/43f3f32743df4c9230749a29b00f700ef4e93878/package.json#L14-L17

**Comment by DavidSchillinger** [comment]
I don't intend to resurrect this issue, I just want to provide some more context for anyone visiting, which I hope is ok:

TypeScript is working on support for `exports`: https://github.com/microsoft/TypeScript/issues/33079

That said, as a _workaround_, the only way I've been able to get it to work in my TS projects is to:
`import filenamify from 'filenamify/filenamify';`

I only do this because I understand the risks.
e.g. I don't get to complain if the path to it changes in a non-major version bump and breaks my setup!

Thank you for `filenamify` :smiley:

**Comment by crucialfelix** [comment]
Granted, this may be something not correctly configured with my build tool or with ts-node, but I am unable to import this in a Node TypeScript project

```bash
❯ /usr/bin/env ts-node "/Users/crucialfelix/github/scanner/cli.ts"
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/crucialfelix/github/scanner/node_modules/filenamify/index.js from /Users/crucialfelix/github/scanner/src/lib/storage.ts not supported.
Instead change the require of index.js in /Users/crucialfelix/github/scanner/src/lib/storage.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/crucialfelix/github/scanner/src/lib/storage.ts:10:38)
    at Module.m._compile (/Users/crucialfelix/.nvm/versions/node/v16.6.2/lib/node_modules/ts-node/dist/index.js:704:29)
```

**Comment by Primajin** [comment]
I could get it to run dirtily 🙈 

with
```ts
// @ts-ignore TS2307: Cannot find module 'filenamify/browser' or its corresponding type declarations.
import filenamify from "filenamify/browser";
```

**Comment by hseager** [comment]
You can also add this to your tsconfig to point the import to the correct type definitions:

`{
  "compilerOptions": {
    "paths": {
      "filenamify/browser": ["./node_modules/filenamify/filenamify.d.ts"]
    }
  }
}`
